name: hierarchyofinfo
favicon: null
layout_spectrum: 0.40409485436975956
typography_spectrum: 0.9865498144645244
title: Hierarchy of Info
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.19002912449650466
  lightness: 0.4685073778964579
  saturation: 0.060554454335942864
  rhythmicContrast: 0.5036815516650677
purpose: []
