name: hierarchyofinfo
favicon: null
layout_spectrum: 0.24719
typography_spectrum: 0.60845
title: Hierarchy of Info
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#34b6d6'
    - '#000000'
    - '#2660aa'
    - '#fe7e15'
  brandStrength: 1
  lightness: 1
  saturation: 0.060554454335942864
  rhythmicContrast: 0.25
purpose: []
