title: Hierarchy of Info
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.06055445433594286
  brandStrength: 0.7222222
  lightness: 0
  brandColors:
    - '#ffffff'
    - '#34b6d6'
    - '#000000'
    - '#2660aa'
    - '#fe7e15'
  rhythmicContrast: 0.25
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: hierarchyofinfo
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.60845
layout_spectrum: 0.4551971
