name: hierarchyofinfo
favicon: null
layout_spectrum: 0.24719
typography_spectrum: 0.19014
title: Hierarchy of Info
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#fffad9'
    - '#585614'
    - '#a49a1c'
    - '#d8da4f'
  brandStrength: 0.19002912449650466
  lightness: 0.4685073778964579
  saturation: 0.060554454335942864
  rhythmicContrast: 1
purpose: []
